### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by thomasklein1982** [SchoolUtils/WebUntis#103]
I'm sorry for the very stupid question, but...

Can I use this library from the browser? Or is it meant to run on a server via NodeJS?

Thank you very much
Thomas.

**Comment by Jeidnx** [comment]
The library was primarily written for nodejs. I dont see any reason why it shouldn't work in the browser, but the readme states [it will probably not work](https://github.com/SchoolUtils/WebUntis#installation).
