### ISSUE TITLE
Is it possible to get a lesson's topic?

### ISSUE THREAD

**Issue by jakob-kruse** [SchoolUtils/WebUntis#36]
I looked at the documentation and the outputs of for example `getOwnClassTimetableForRange` but cannot seem to find anything

**Comment by TheNoim** [comment]
Never heard of a lesson topic. Where can I find this in the user interface (App or WebUntis)?

**Comment by jakob-kruse** [comment]
Sorry for the late response. It is called Teaching Content. It comes up as a tab when you open a lesson

**Comment by TheNoim** [comment]
I know that there is the lesson text and substitution text. Is the teaching content new?

**Comment by jakob-kruse** [comment]
I dont know when it got added, sorry. Maybe [this](https://hastebin.com/agevefukis.json) can help. Its the response i get in the browser when i open the details of a lesson.

**Comment by elias-knodel** [comment]
@jakob-kruse I didn't see this issue until now but a couple months ago i extended the WebUntis class and build a function to get the lesson topic. If you still need it here is my solution: https://gist.github.com/elias-knodel/68170188766956d9475cf99eeed9e260

**Comment by jakob-kruse** [comment]
Thats great! I found my own solution by "reversing the api" myself now, but maybe ill rewrite it with this

**Comment by TheNoim** [comment]
Maybe you could do a pull request :) ?

**Comment by elias-knodel** [comment]
I will try but first i looked over it with my friend and i found an issue in my code above:
I accidentally hardcoded the "&elemid=10487" part.

![image](https://user-images.githubusercontent.com/42189915/116626750-1895a100-a94c-11eb-8d67-9461a096ccb7.png)

It is custom for everybody and if i find a way to make it customizable i will create a PR. 👍🏼

**Comment by TheNoim** [comment]
element type 5 is a student. I expect the element id just to be your own id. Example invocation: https://github.com/SchoolUtils/WebUntis/blob/134512baf906ee360a0722a394915e115eb73e27/index.js#L228 and https://github.com/SchoolUtils/WebUntis/blob/134512baf906ee360a0722a394915e115eb73e27/index.js#L309
