### ISSUE TITLE
TypeError with _buildCookies()

### ISSUE THREAD

**Issue by finki70** [SchoolUtils/WebUntis#37]
Hi, this error occurred in my setup, I dont know where it is from, I only got it in sentry....

![image](https://user-images.githubusercontent.com/38655889/101291132-d043de00-3806-11eb-9770-d8cb4e99aa05.png)

**Comment by TheNoim** [comment]
Maybe the logout method is broken and it was used before this. This is the only time when sessionInformation is null.

**Comment by TheNoim** [comment]
This should fix it: 9502e5f6a8fda250a8a848c6cf28ca84a0413cc7
