### ISSUE TITLE
Website Not there

### ISSUE THREAD

**Issue by xhendrikg** [SchoolUtils/WebUntis#41]
The website tell that the page is not there

**Comment by dunklesToast** [comment]
You mean the documentation, right?
I guess we missed that back when we moved the repository to a new GitHub Namespace. We'll take a look!

**Comment by xhendrikg** [comment]
I mean the custom domain

**Comment by dunklesToast** [comment]
This one, right?

https://noim.me/WebUntis/

**Comment by xhendrikg** [comment]
> This one, right?
> 
> https://noim.me/WebUntis/

Yes

**Comment by elias-knodel** [comment]
There was a GitHub Pages deployment a few hours ago and [schoolutils.noim.me](http://schoolutils.noim.me) with the documentation is now reachable. Will this name change or stay so?

**Comment by TheNoim** [comment]
I am not sure. I will probably change it to webuntis.noim.me, because it is more appropriated. Sadly, DNS change and ssl cert generation by github takes some time. Hopefully in 24h webuntis.noim.me will be the final domain.
