### ISSUE TITLE
Timetable doesn't get returned in order

### ISSUE THREAD

**Issue by Amenofisch** [SchoolUtils/WebUntis#46]
Hey,

When I get my Timetable using `untis.getOwnTimetableForToday();`, it gets returned in a completely random order.

Is there a way to sort it according to `startTime` or `endTime`?

If so please let me know. :)

**Comment by TheNoim** [comment]
You can sort with js itself. However, as far as I know there is no way to do it server side.

**Comment by Amenofisch** [comment]
Hey, a little follow up to how i fixed it:

`var sortedInput = timetable.slice().sort((a, b) => a.startTime- b.startTime);`
