### ISSUE TITLE
Cancelled Lesson

### ISSUE THREAD

**Issue by devskar** [SchoolUtils/WebUntis#71]
Is there a way to check if a lesson on a specific date is cancelled?

**Comment by luwol03** [comment]
Yes, just get the timetable for that date and filter for `lesson.code === "canceled"` [[see](https://github.com/SchoolUtils/WebUntis/blob/master/index.d.ts#L57)]

**Comment by luwol03** [comment]
@devskar Does this work so that this issue could be closed?

**Comment by devskar** [comment]
Yes I’m sorry for the late reply.
