### ISSUE TITLE
Logical error in v2?

### ISSUE THREAD

**Issue by DEVTomatoCake** [SchoolUtils/WebUntis#89]
Just updated to v2 and well, it apparently doesnt like the server anymore:
```js
Error: Failed to login. Server didn't return a session id.
    at WebUntisQR._otpLogin (/home/container/node_modules/webuntis/dist/webuntis.js:648:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebUntisQR.login (/home/container/node_modules/webuntis/dist/webuntis.js:748:12)
```

Caused by (compiled) L648:
```js
if (response.headers && response.headers["set-cookie"] && this._getCookieFromSetCookie(response.headers["set-cookie"]))
      throw new Error("Failed to login. Server didn't return a session id.");
```
But the last check in the if clause doesnt make sense, it should have a `!` in front of it - esp as the next line uses it:
```js
const sessionId = this._getCookieFromSetCookie(response.headers["set-cookie"]);
```

Added the `!` in my code and its working completely fine then 🤷

Uncompiled: https://github.com/SchoolUtils/WebUntis/blob/479c60b34702b943d48c1787d26961351192d167/index.js#L862

**Comment by TheNoim** [comment]
You are right. This was a mistake.

**Comment by TheNoim** [comment]
Try v2.0.1
