### ISSUE TITLE
Getting a 'server didn't return any results' for timetable with parallel lessons

### ISSUE THREAD

**Issue by thyed** [SchoolUtils/WebUntis#95]
Unfortunately, for 11th and 12th grade the school decided to put all lessons in everybody's timetables. So my kids see lessons they don't have. However, it would still be nice to see which lessons are omitted.

But retrieving a timetable leads to an error. Not sure why. Potentially, because of the parallel lessons?

Example program
```
import { WebUntis } from 'webuntis';
const untis = new WebUntis('...');
await untis.login();
console.log(await untis.getTimetableForToday())
```
returns

```
C:\dev\Untis\node_modules\webuntis\dist\webuntis.js:564
      throw new Error("Server didn't return any result.");

Error: Server didn't return any result.
    at Base._request (C:\dev\Untis\node_modules\webuntis\dist\webuntis.js:564:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Base.getTimetableForToday (C:\dev\Untis\node_modules\webuntis\dist\webuntis.js:340:12)
    at async file:///C:/dev/Untis/app.js:13:13
```

I would love to provide you with the login data, if you have time to look further into this.

**Comment by thyed** [comment]
My fault. 'getOwnClassTimetableForRange' seems to work.

**Comment by luwol03** [comment]
Hello @thyed,

> But retrieving a timetable leads to an error. Not sure why. Potentially, because of the parallel lessons?

I guess this is because your school may block access to the class timetable which you get with `getTimetableForToday()`. That's why nothing is returned. You can find this out if you want by clicking on your name (in untis mobile) on the top and see if other classes names appear. Then try to click on one.
