### ISSUE TITLE
Where to get School URL From?

### ISSUE THREAD

**Issue by TryAnixx** [SchoolUtils/WebUntis#96]
Hey, i dont know my School Server URL.
I can find my School here: https://webuntis.com/
Can i take the url from the school login of this website?
Cant see any Server/URL Info in the WebUntis App.

Thanks for your help!

**Comment by TheNoim** [comment]
> Can i take the url from the school login of this website?

Yes, use the host of your login page.

**Comment by Le0X8** [comment]
If you've found your school on webuntis.com and clicked on it, you should be redirected to something like that:
`herakles.webuntis.com/WebUntis/?school=gwgym-wetter`

So my domain name is `herakles.webuntis.com`
and my school's name is: `gwgym-wetter`

This worked fine for me :)
