### ISSUE TITLE
What is the base url for the school?

### ISSUE THREAD

**Issue by tevzselcan** [SchoolUtils/WebUntis#99]
Im trying to get the timetables with this code, but I don't know what the base url is for my[school](https://ajax.webuntis.com/WebUntis/?school=sc-celje#/basic/login), the current code:
```
import { WebUntisAnonymousAuth, WebUntisElementType } from "webuntis";

const untis = new WebUntisAnonymousAuth(
  "SC-Celje",
  "https://ajax.webuntis.com/WebUntis/?school=sc-celje"
);

await untis.login();
const classes = await untis.getClasses();
const timetable = await untis.getTimetableForToday(
  classes[10].id,
  WebUntisElementType.CLASS
);
console.log(timetable);
```

**Comment by TheNoim** [comment]
The baseurl for you is `ajax.webuntis.com`.
However, I don't think your instance supports anonymous auth.

**Comment by tevzselcan** [comment]
Thanks, got it working with that :)
